### ISSUE TITLE
Mixpanel.sharedWithInstanceToken on Readme is undefined

### ISSUE THREAD

**Issue by mikeccuk2005** [projetoeureka/react-native-mixpanel-bridge#3]
Sir
The readme you mention Mixpanel.sharedWithInstanceToken which is undefined
However I checked the android native function is Mixpanel.sharedInstanceWithToken

Please verify your Readme.

**Comment by ts-ign0re** [comment]
+1 need to update readme with manual instructions for android

**Comment by cneilwarner** [comment]
+1

**Comment by duailibe** [comment]
Hi all, sorry about this.. we don't this anymore, we have changed to https://github.com/davodesign84/react-native-mixpanel
